export interface CreateCustomAppIntegration {
    /**
     * indicates if an oauth client-secret should be generated
     */
    confidential?: boolean;
    /**
     * The oauth app integration ID.
     */
    integration_id: string;
    /**
     * name of the custom oauth app
     */
    name?: string;
    /**
     * List of oauth redirect urls
     */
    redirect_urls?: Array<string>;
    /**
     * Token access policy
     */
    token_access_policy?: TokenAccessPolicy;
}
export interface CreateCustomAppIntegrationOutput {
    /**
     * oauth client-id generated by the Databricks
     */
    client_id?: string;
    /**
     * oauth client-secret generated by the Databricks if this is a confidential
     * oauth app client-secret will be generated.
     */
    client_secret?: string;
    /**
     * unique integration id for the custom oauth app
     */
    integration_id?: string;
}
export interface CreatePublishedAppIntegration {
    /**
     * app_id of the oauth published app integration. For example power-bi,
     * tableau-deskop
     */
    app_id?: string;
    /**
     * The oauth app integration ID.
     */
    integration_id: string;
    /**
     * Token access policy
     */
    token_access_policy?: TokenAccessPolicy;
}
export interface CreatePublishedAppIntegrationOutput {
    /**
     * unique integration id for the published oauth app
     */
    integration_id?: string;
}
/**
 * Delete Custom OAuth App Integration
 */
export interface DeleteCustomAppIntegrationRequest {
    /**
     * The oauth app integration ID.
     */
    integration_id: string;
}
/**
 * Delete Published OAuth App Integration
 */
export interface DeletePublishedAppIntegrationRequest {
    /**
     * The oauth app integration ID.
     */
    integration_id: string;
}
export interface GetCustomAppIntegrationOutput {
    /**
     * oauth client id of the custom oauth app
     */
    client_id?: string;
    /**
     * indicates if an oauth client-secret should be generated
     */
    confidential?: boolean;
    /**
     * name of the custom oauth app
     */
    name?: string;
    /**
     * List of oauth redirect urls
     */
    redirect_urls?: Array<string>;
    /**
     * Token access policy
     */
    token_access_policy?: TokenAccessPolicy;
}
/**
 * Get OAuth Custom App Integration
 */
export interface GetCustomAppIntegrationRequest {
    /**
     * The oauth app integration ID.
     */
    integration_id: string;
}
export interface GetPublishedAppIntegrationOutput {
    /**
     * app-id of the published app integration
     */
    app_id?: string;
    /**
     * unique integration id for the published oauth app
     */
    integration_id?: string;
    /**
     * name of the published oauth app
     */
    name?: string;
    /**
     * Token access policy
     */
    token_access_policy?: TokenAccessPolicy;
}
/**
 * Get OAuth Published App Integration
 */
export interface GetPublishedAppIntegrationRequest {
    /**
     * The oauth app integration ID.
     */
    integration_id: string;
}
export interface TokenAccessPolicy {
    /**
     * access token time to live in minutes
     */
    access_token_ttl_in_minutes?: any;
    /**
     * refresh token time to live in minutes
     */
    refresh_token_ttl_in_minutes?: any;
}
export interface UpdateCustomAppIntegration {
    /**
     * The oauth app integration ID.
     */
    integration_id: string;
    /**
     * List of oauth redirect urls to be updated in the custom oauth app
     * integration
     */
    redirect_urls?: Array<string>;
    /**
     * Token access policy to be updated in the custom oauth app integration
     */
    token_access_policy?: TokenAccessPolicy;
}
export interface UpdatePublishedAppIntegration {
    /**
     * The oauth app integration ID.
     */
    integration_id: string;
    /**
     * Token access policy to be updated in the published oauth app integration
     */
    token_access_policy?: TokenAccessPolicy;
}
export interface EmptyResponse {
}
//# sourceMappingURL=model.d.ts.map